name             'notepadpp'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/notepadpp'
issues_url       'https://github.com/windowschefcookbooks/notepadpp/issues'
license          'Apache 2.0'
description      'Installs/Configures Notepad++'
version          '1.0.0'
