name             'notepadpp'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
source_url       'https://github.com/sous-chefs/notepadpp'
issues_url       'https://github.com/sous-chefs/notepadpp/issues'
chef_version     '>= 15.3'
license          'Apache-2.0'
description      'Installs/Configures Notepad++'
version          '2.0.4'
supports         'windows'
depends          'windows'
