name             'notepadpp'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/notepadpp'
issues_url       'https://github.com/windowschefcookbooks/notepadpp/issues'
chef_version     '>= 13.0'
license          'Apache-2.0'
description      'Installs/Configures Notepad++'
version          '2.0.0'
supports         'windows'
depends          'windows'
